# Generated by Django 4.1.3 on 2022-11-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_remove_post_uid_post_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
